export const albuns = [
  {
    imagem: "./src/assets/img/agepe.webp",
    artista: "Agepê",
    titulo: "Moro Onde Não Mora Ninguém",
    ano: 1975,
    pais: "Brasil",
    estilo: ["Samba"],
  },
  {
    imagem: "./src/assets/img/alceu_valenca.webp",
    artista: "Alceu Valença",
    titulo: "Cavalo De Pau",
    ano: 1982,
    pais: "Brasil",
    estilo: ["MPB", "Forró", "Reggae"],
  },
  {
    imagem: "./src/assets/img/catia.webp",
    artista: "Cátia de França",
    titulo: "20 Palavras Ao Redor Do Sol",
    ano: 1979,
    pais: "Brasil",
    estilo: ["MPB", "Forró", "Folk Rock"],
  },
  {
    imagem: "./src/assets/img/ednardo.webp",
    artista: "Ednardo",
    titulo: "O Romance Do Pavão Mysteriozo",
    ano: 1974,
    pais: "Brasil",
    estilo: ["MPB", "Folk Rock"],
  },
  // {
  //   imagem: "./src/assets/img/gilberto_gil_dois.webp",
  //   artista: "Gilberto Gil",
  //   titulo: "Refavela",
  //   ano: 1977,
  //   pais: "Brasil",
  //   estilo: ["MPB"],
  // },
  {
    imagem: "./src/assets/img/gilberto_gil.webp",
    artista: "Gilberto Gil",
    titulo: "Refazenda",
    ano: 1975,
    pais: "Brasil",
    estilo: ["Samba", "MPB"],
  },
];
